In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

import os, sys
module_path = os.path.abspath(os.path.join(os.pardir))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
from src.table_encoder import *
from src.metrics import *

In [3]:
movies = pd.read_csv('../data/csv/movies.csv')

In [4]:
ratings = pd.read_csv('../data/csv/ratings.csv')

In [5]:
tags = pd.read_csv('../data/csv/tags.csv')

In [6]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [7]:
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [8]:
tags = tags.drop('timestamp', axis = 1)
tags

userId  movieId               tag
0          2    60756             funny
1          2    60756   Highly quotable
2          2    60756      will ferrell
3          2    89774      Boxing story
4          2    89774               MMA
...      ...      ...               ...
3678     606     7382         for katie
3679     606     7936           austere
3680     610     3265            gun fu
3681     610     3265  heroic bloodshed
3682     610   168248  Heroic Bloodshed

[3683 rows x 3 columns]

In [15]:
encoded_tags = tag_encoder(tags)
encoded_genres = genre_encoder(movies)

In [10]:
compare_movie(1, 2, encoded_genres)
compare_all_movies(1, encoded_genres)

[array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.91287093]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442719]]),
 array([[0.89442

In [11]:
joined = movies.set_index('movieId').join(ratings.set_index('movieId'))
joined = joined[~joined['userId'].isna()] 
joined

title  \
movieId                                              
1                                 Toy Story (1995)   
1                                 Toy Story (1995)   
1                                 Toy Story (1995)   
1                                 Toy Story (1995)   
1                                 Toy Story (1995)   
...                                            ...   
193581   Black Butler: Book of the Atlantic (2017)   
193583                No Game No Life: Zero (2017)   
193585                                Flint (2017)   
193587         Bungo Stray Dogs: Dead Apple (2018)   
193609         Andrew Dice Clay: Dice Rules (1991)   

                                              genres  userId  rating  \
movieId                                                                
1        Adventure|Animation|Children|Comedy|Fantasy     1.0     4.0   
1        Adventure|Animation|Children|Comedy|Fantasy     5.0     4.0   
1        Adventure|Animation|Children|Comedy|Fantasy     7.0     4.5   
1        Adventure|Animation|Children|Comedy|Fantasy    15.0     2.5   
1        Adventure|Animation|Children|Comedy|Fantasy    17.0     4.5   
...                                              ...     ...     ...   
193581               Action|Animation|Comedy|Fantasy   184.0     4.0   
193583                      Animation|Comedy|Fantasy   184.0     3.5   
193585                                         Drama   184.0     3.5   
193587                              Action|Animation   184.0     3.5   
193609                                        Comedy   331.0     4.0   

            timestamp  
movieId                
1        9.649827e+08  
1        8.474350e+08  
1        1.106636e+09  
1        1.510578e+09  
1        1.305696e+09  
...               ...  
193581   1.537109e+09  
193583   1.537110e+09  
193585   1.537110e+09  
193587   1.537110e+09  
193609   1.537158e+09  

[100836 rows x 5 columns]

In [12]:
merged = pd.merge(ratings, encoded_tags, how = 'left', left_on = ['userId','movieId'], right_on = ['userId','movieId'])
merged = pd.merge(merged, movies, how = 'left', on = 'movieId').fillna(0)
merged

userId  movieId  rating   timestamp  Huey Long  Cold  Bad story  \
0            1        1     4.0   964982703        0.0   0.0        0.0   
1            1        3     4.0   964981247        0.0   0.0        0.0   
2            1        6     4.0   964982224        0.0   0.0        0.0   
3            1       47     5.0   964983815        0.0   0.0        0.0   
4            1       50     5.0   964982931        0.0   0.0        0.0   
...        ...      ...     ...         ...        ...   ...        ...   
100831     610   166534     4.0  1493848402        0.0   0.0        0.0   
100832     610   168248     5.0  1493850091        0.0   0.0        0.0   
100833     610   168250     5.0  1494273047        0.0   0.0        0.0   
100834     610   168252     5.0  1493846352        0.0   0.0        0.0   
100835     610   170875     3.0  1493846415        0.0   0.0        0.0   

        Venice  milkshake  philosopical  ...  generation X  cattle drive  \
0          0.0        0.0           0.0  ...           0.0           0.0   
1          0.0        0.0           0.0  ...           0.0           0.0   
2          0.0        0.0           0.0  ...           0.0           0.0   
3          0.0        0.0           0.0  ...           0.0           0.0   
4          0.0        0.0           0.0  ...           0.0           0.0   
...        ...        ...           ...  ...           ...           ...   
100831     0.0        0.0           0.0  ...           0.0           0.0   
100832     0.0        0.0           0.0  ...           0.0           0.0   
100833     0.0        0.0           0.0  ...           0.0           0.0   
100834     0.0        0.0           0.0  ...           0.0           0.0   
100835     0.0        0.0           0.0  ...           0.0           0.0   

        parenthood  It was melodramatic and kind of dumb  parody  \
0              0.0                                   0.0     0.0   
1              0.0                                   0.0     0.0   
2              0.0                                   0.0     0.0   
3              0.0                                   0.0     0.0   
4              0.0                                   0.0     0.0   
...            ...                                   ...     ...   
100831         0.0                                   0.0     0.0   
100832         0.0                                   0.0     0.0   
100833         0.0                                   0.0     0.0   
100834         0.0                                   0.0     0.0   
100835         0.0                                   0.0     0.0   

        Jesse Eisenberg  highschool  emma thompson  \
0                   0.0         0.0            0.0   
1                   0.0         0.0            0.0   
2                   0.0         0.0            0.0   
3                   0.0         0.0            0.0   
4                   0.0         0.0            0.0   
...                 ...         ...            ...   
100831              0.0         0.0            0.0   
100832              0.0         0.0            0.0   
100833              0.0         0.0            0.0   
100834              0.0         0.0            0.0   
100835              0.0         0.0            0.0   

                                 title  \
0                     Toy Story (1995)   
1              Grumpier Old Men (1995)   
2                          Heat (1995)   
3          Seven (a.k.a. Se7en) (1995)   
4           Usual Suspects, The (1995)   
...                                ...   
100831                    Split (2017)   
100832   John Wick: Chapter Two (2017)   
100833                  Get Out (2017)   
100834                    Logan (2017)   
100835  The Fate of the Furious (2017)   

                                             genres  
0       Adventure|Animation|Children|Comedy|Fantasy  
1                                    Comedy|Romance  
2                             Action|Crime|Thriller  
3      

In [13]:
trimmed = joined.reset_index()[['movieId', 'userId', 'rating']]
trimmed

movieId  userId  rating
0             1     1.0     4.0
1             1     5.0     4.0
2             1     7.0     4.5
3             1    15.0     2.5
4             1    17.0     4.5
...         ...     ...     ...
100831   193581   184.0     4.0
100832   193583   184.0     3.5
100833   193585   184.0     3.5
100834   193587   184.0     3.5
100835   193609   331.0     4.0

[100836 rows x 3 columns]

In [14]:
users_set = trimmed['userId'].unique()
users_set.sort()

movie_set = trimmed['movieId'].unique()
movie_set.sort()

user_frame = pd.DataFrame(index = users_set, columns = movie_set)
user_frame = user_frame.fillna(0)

counter = 0
ten_precent = int(trimmed.shape[0] / 10)
for row in trimmed.iterrows():
    counter += 1
    if counter % ten_precent == 0:
        print(counter // ten_precent * 10, '% of the way done')
    row = row[1]
    _userId = row['userId']
    _movieId = row['movieId']
    user_frame.loc[_userId][_movieId] = row['rating']

10 % of the way done
20 % of the way done
30 % of the way done
40 % of the way done
50 % of the way done
60 % of the way done
70 % of the way done
80 % of the way done
90 % of the way done
100 % of the way done


In [15]:
user_num = 5
new_user = user_frame.loc[user_num]
new_frame = user_frame.copy().drop(user_num)

sims = []
for row in new_frame.iterrows():
    userId = row[0]
    row = row[1]
    sims.append((userId, cosine_similarity([row], [new_user])[0][0]))
    
sims.sort(key = lambda x: x[1], reverse = True)



def get_top_5(user_frame, user_info, userId_other, movies):
    user_info_other = user_frame.iloc[userId_other]

    m = (user_info_other * user_info)
    top_five = m[m > 0].sort_values(ascending = False)[0: 5]

    for movie_id in top_five.index:
        top_five.loc[movie_id] = movies.set_index('movieId').loc[movie_id]['title']
    return top_five

top_five = []
index = 0
while len(top_five) < 5 and index < len(sims):
    closest_user = int(sims[index][0])
    new_movies = list(get_top_5(new_frame, new_user, closest_user, movies))
    for movie in new_movies:
        if movie not in top_five:
            top_five.append(movie)
    index += 1
    
top_five = top_five[:5]

In [16]:
top_five

['Usual Suspects, The (1995)',
 'Shawshank Redemption, The (1994)',
 'Pulp Fiction (1994)',
 'Terminator 2: Judgment Day (1991)',
 "Schindler's List (1993)"]

In [62]:
#old code
'''
users_set = trimmed['userId'].unique()
users_set.sort()
user_frame = pd.DataFrame(users_set, columns = ['userId'])
user_frame = user_frame.set_index('userId')

movies_set = trimmed['movieId'].unique()
movies_set.sort()
movie_vector_blank = pd.DataFrame([np.zeros(len(movies_set))], columns = movies_set)

user_frame['movie_vect'] = [movie_vector_blank.copy() for i in range(user_frame.shape[0])]

counter = 0
ten_precent = int(trimmed.shape[0] / 10)
for row in trimmed.iterrows():
    counter += 1
    if counter % ten_precent == 0:
        print(counter // ten_precent * 10, '% of the way done')
    row = row[1]
    _userId = row['userId']
    _movieId = row['movieId']
    user_frame.loc[_userId]['movie_vect'][_movieId] = row['rating']
'''

10 % of the way done
20 % of the way done
30 % of the way done
40 % of the way done
50 % of the way done
60 % of the way done
70 % of the way done
80 % of the way done
90 % of the way done
100 % of the way done


In [66]:
#old code
'''
user_num = 1
new_user = user_frame.loc[user_num]['movie_vect']
new_frame = user_frame.copy().drop(user_num)

sims = []
for row in new_frame.iterrows():
    userId = row[0]
    row = row[1]
    sims.append((userId, cosine_similarity(row['movie_vect'], new_user)[0][0]))
    
sims.sort(key = lambda x: x[1], reverse = True)
closest_user = int(sims[0][0])
closest_user = new_frame.iloc[closest_user]['movie_vect']

m = (closest_user * new_user).T
top_five = m[m[0] > 0].sort_values(by = 0, ascending = False)[0: 5]

for movie_id in top_five.index:
    top_five.loc[movie_id] = movies.set_index('movieId').loc[movie_id]['title']
'''


In [14]:
spark = SparkSession(SparkContext())

ratings = spark.createDataFrame(trimmed)
(training, test) = ratings.randomSplit([0.8, 0.2])

als=ALS(maxIter=5,regParam=0.09,rank=25,userCol="reviewerID_index",itemCol="asin_index",ratingCol="overall",coldStartStrategy="drop",nonnegative=True)
model=als.fit(training)

Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.net.BindException: Can't assign requested address: Service 'sparkDriver' failed after 16 retries (on a random free port)! Consider explicitly setting the appropriate binding address for the service 'sparkDriver' (for example spark.driver.bindAddress for SparkDriver) to the correct binding address.
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
